# Generated by Django 6.0.2 on 2026-03-04 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название жанра')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер сезона')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название сезона')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название фильма')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Название (англ.)')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='posters/', verbose_name='Постер')),
                ('trailer', models.URLField(blank=True, verbose_name='Ссылка на трейлер')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео файл')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('director', models.CharField(max_length=200, verbose_name='Режиссёр')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность (мин.)')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('genre', models.ManyToManyField(to='films.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер серии')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название серии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='episodes/', verbose_name='Видео файл')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('duration', models.PositiveIntegerField(default=45, verbose_name='Длительность (мин.)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='films.season')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
                'ordering': ['number'],
                'unique_together': {('season', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название сериала')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Название (англ.)')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='posters/', verbose_name='Постер')),
                ('trailer', models.URLField(blank=True, verbose_name='Ссылка на трейлер')),
                ('year_start', models.PositiveIntegerField(verbose_name='Год начала')),
                ('year_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год окончания')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('director', models.CharField(max_length=200, verbose_name='Режиссёр')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('genre', models.ManyToManyField(to='films.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='films.series'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='films.film')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'film')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Оценка')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='films.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'film')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('series', 'number')},
        ),
        migrations.CreateModel(
            name='ViewingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('last_position', models.PositiveIntegerField(default=0, verbose_name='Последняя позиция (сек)')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Общая длительность (сек)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Просмотрено полностью')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='films.episode')),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='films.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История просмотров',
                'verbose_name_plural': 'История просмотров',
                'ordering': ['-watched_at'],
                'unique_together': {('user', 'film', 'episode')},
            },
        ),
    ]
